[package]
name = "s3ers"
version = "0.0.1"
authors = ["Marc 'risson' Schmitt <marc.schmitt@risson.space>"]
repository = "https://gitlab.com/s3ers/s3ers"
readme = "README.md"
license-file = "LICENSE"
publish = false # this is not ready yet
edition = "2018"

[dependencies]
